# frontend/Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Set environment variables
ENV PORT 7860
ENV BACKEND_API_URL=http://backend.jamesstaud.com:8000/query

# Expose the port the app runs on
EXPOSE 7860

# Command to run the Gradio app
CMD ["python", "app.py"]