# .digitalocean.app.yaml
name: jamesstaud-website
services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    build_command: pip install -r backend/requirements.txt
    run_command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${OPENAI_API_KEY}  # Set from environment variables
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    build_command: pip install -r frontend/requirements.txt
    run_command: python frontend/app.py
    envs:
      - key: GRADIO_THEME
        scope: RUN_AND_BUILD_TIME
        value: light  # Example variable
  - name: mongodb
    image: mongo:latest
    envs:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: password