name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - initial-app

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        id: repo
        run: | 
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME#*/}"
          echo "::set-output name=repo::$(echo $REPO_NAME | awk '{print tolower($0)}')"
      
      - name: Build the backend Docker image
        run: |
          docker build . --file ./backend/dockerfile --tag ${{ steps.repo.outputs.repo }}-backend:latest

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        id: repo
        run: | 
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME#*/}"
          echo "::set-output name=repo::$(echo $REPO_NAME | awk '{print tolower($0)}')"
      
      - name: Build the frontend Docker image
        run: |
          docker build . --file ./frontend/dockerfile --tag ${{ steps.repo.outputs.repo }}-frontend:latest

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - uses: actions/checkout@v2

      - name: Run the backend container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          docker run -d -p 8000:8000 \ 
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          -e OPENAI_ORGANIZATION_ID=${{ secrets.OPENAI_ORGANIZATION_ID }} \
          -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
          ${{ steps.repo.outputs.repo }}-backend:latest

      - name: Push the backend image to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ${{ steps.repo.outputs.repo }}-backend:latest ghcr.io/${{ github.repository }}/${{ steps.repo.outputs.repo }}-backend:latest
          docker push ghcr.io/${{ github.repository }}/${{ steps.repo.outputs.repo }}-backend:latest

      - name: Deploy backend to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ steps.repo.outputs.repo }}-backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v2

      - name: Run the frontend container
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
        run: |
          docker run -d -p 8080:8080 --env-file .env -e BACKEND_API_URL=${{ secrets.BACKEND_API_URL }} ${{ steps.repo.outputs.repo }}-frontend:latest

      - name: Push the frontend image to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ${{ steps.repo.outputs.repo }}-frontend:latest ghcr.io/${{ github.repository }}/${{ steps.repo.outputs.repo }}-frontend:latest
          docker push ghcr.io/${{ github.repository }}/${{ steps.repo.outputs.repo }}-frontend:latest

      - name: Deploy frontend to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ steps.repo.outputs.repo }}-frontend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}