name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - initial-app

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and publish a Docker image for backend
        uses: macbre/push-to-ghcr@master
        with:
          image_name: jamesstaudcom_backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: backend/Dockerfile

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and publish a Docker image for frontend
        uses: macbre/push-to-ghcr@master
        with:
          image_name: jamesstaudcom_frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: frontend/Dockerfile

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
      - uses: actions/checkout@v2

      - name: Run the backend container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          docker run -d -p 8000:8000 \ 
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          -e OPENAI_ORGANIZATION_ID=${{ secrets.OPENAI_ORGANIZATION_ID }} \
          -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
          ghcr.io/${{ github.repository }}/jamesstaudcom_backend:latest

      - name: Deploy backend to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: jamesstaudcom_backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v2

      - name: Run the frontend container
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
        run: |
          docker run -d -p 8080:8080 \
            -e BACKEND_API_URL=${{ secrets.BACKEND_API_URL }} \
            ghcr.io/${{ github.repository }}/jamesstaudcom_frontend:latest

      - name: Deploy frontend to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: jamesstaudcom_frontend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}